apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-ro
  namespace: rollout
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  selector:
    matchLabels:
      app: nginx
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
